apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: larsmeeuws/mlops-api:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
      #     volumeMounts:
      #       - name: model-volume
      #         mountPath: /app/models/
      # volumes:
      #   - name: model-volume
      #     persistentVolumeClaim:
      #       claimName: model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

