# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: model-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     # path: "/Users/Lars/Documents/school/MLOps/project/models"  # Internally adds `/mnt/host/c/` before this string
#     # path: "/run/desktop/mnt/host/c/Users/Lars/Documents/school/MLOps/project/models"
#     # path: "/run/desktop/mnt/host/c/tmp"
#     path: "/"  # this mounts the root of some random debian distro for some reason (not docker-desktop)?? host files aren't retrievable from here
#     type: Directory
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: model-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: manual
