name: Deploy to kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rollout Restart API
        run: kubectl rollout restart deployment/api

      - name: Rollout Restart Frontend
        run: kubectl rollout restart deployment/frontend
