name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: larsmeeuws/mlops-api:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: larsmeeuws/mlops-frontend:latest


  deploy-kubernetes:
    runs-on: self-hosted
    needs: build-and-push-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rollout Restart API
        run: kubectl rollout restart deployment/api

      - name: Rollout Restart Frontend
        run: kubectl rollout restart deployment/frontend
